# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 200000
evaluation_epsilon: 0.05
lr: 0.0003 # Learning rate for agents

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 0.01


obs_agent_id: True
obs_last_action: False
obs_individual_obs: False


# use the Q_Learner to train
standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix"
use_rnn: True
mixing_embed_dim: 64
hypernet_layers: 2
hypernet_embed: 64
use_cuda: True
name: "qmix"
